[custom]
clash_rule_base=https://gh.168828.xyz/https://raw.githubusercontent.com/gdfsnhsw/AutoClash/main/subconverter/all_base.tpl

ruleset=🎯 全球直连,clash-classic:https://gh.168828.xyz/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/LocalAreaNetwork.yaml
ruleset=🎯 全球直连,clash-classic:https://gh.168828.xyz/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/UnBan.yaml
ruleset=🛑 广告拦截,clash-classic:https://gh.168828.xyz/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml
ruleset=🍃 应用净化,clash-classic:https://gh.168828.xyz/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanProgramAD.yaml
ruleset=📢 谷歌FCM,clash-classic:https://gh.168828.xyz/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleFCM.yaml
ruleset=🏵 SpeedTest,clash-classic:https://gh.168828.xyz/https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/SpeedTest.yaml
ruleset=🎯 全球直连,clash-classic:https://gh.168828.xyz/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleCN.yaml
ruleset=Ⓜ️ 微软云盘,clash-classic:https://gh.168828.xyz/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/OneDrive.yaml
ruleset=🍎 苹果服务,clash-classic:https://gh.168828.xyz/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Apple.yaml
ruleset=📲 Telegram,clash-classic:https://gh.168828.xyz/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Telegram.yaml
ruleset=🎶 网易音乐,clash-classic:https://gh.168828.xyz/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/NetEaseMusic.yaml
ruleset=🎮 国际游戏,clash-classic:https://gh.168828.xyz/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Epic.yaml
ruleset=🎮 国际游戏,clash-classic:https://gh.168828.xyz/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Sony.yaml
ruleset=🎮 国际游戏,clash-classic:https://gh.168828.xyz/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Steam.yaml
ruleset=📹 Youtube,clash-classic:https://gh.168828.xyz/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/YouTube.yaml
ruleset=🎥 Netflix,clash-classic:https://gh.168828.xyz/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Netflix.yaml
ruleset=🎬 DisneyPlus,clash-classic:https://gh.168828.xyz/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/DisneyPlus.yaml
ruleset=📺 巴哈姆特,clash-classic:https://gh.168828.xyz/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Bahamut.yaml
ruleset=🌏 国内媒体,clash-classic:https://gh.168828.xyz/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaMedia.yaml
ruleset=🌍 国外媒体,clash-classic:https://gh.168828.xyz/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyMedia.yaml
ruleset=🌏 出海媒体,clash-classic:https://gh.168828.xyz/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/BilibiliHMT.yaml
ruleset=🚀 节点选择,clash-classic:https://gh.168828.xyz/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyGFWlist.yaml
ruleset=🎯 全球直连,clash-ipcidr:https://gh.168828.xyz/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaIp.yaml
ruleset=🎯 全球直连,clash-classic:https://gh.168828.xyz/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaDomain.yaml
ruleset=🎯 全球直连,clash-ipcidr:https://gh.168828.xyz/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaCompanyIp.yaml
ruleset=🎯 全球直连,clash-classic:https://gh.168828.xyz/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Download.yaml
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]🌀 手动切换`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧩 专用线路`[]🎯 全球直连
custom_proxy_group=🌀 手动切换`select`.*
custom_proxy_group=📹 Youtube`select`[]🚀 节点选择`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧩 专用线路`[]🌀 手动切换`[]🎯 全球直连
custom_proxy_group=🎥 Netflix`select`[]🎥 奈飞节点`[]🚀 节点选择`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧩 专用线路`[]🌀 手动切换`[]🎯 全球直连
custom_proxy_group=🎬 DisneyPlus`select`[]🚀 节点选择`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧩 专用线路`[]🌀 手动切换`[]🎯 全球直连
custom_proxy_group=🏵 SpeedTest`select`[]🎯 全球直连`[]🚀 节点选择`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧩 专用线路`[]🌀 手动切换
custom_proxy_group=📺 巴哈姆特`select`[]🇨🇳 台湾节点`[]🚀 节点选择`[]🧩 专用线路`[]🌀 手动切换`[]🎯 全球直连
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧩 专用线路`[]🌀 手动切换`[]🎯 全球直连
custom_proxy_group=🌏 国内媒体`select`[]🎯 全球直连`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🧩 专用线路`[]🌀 手动切换
custom_proxy_group=🌏 出海媒体`select`[]🎯 全球直连`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🧩 专用线路`[]🌀 手动切换
custom_proxy_group=📢 谷歌FCM`select`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🧩 专用线路`[]🌀 手动切换`[]🎯 全球直连
custom_proxy_group=Ⓜ️ 微软云盘`select`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🧩 专用线路`[]🌀 手动切换`[]🎯 全球直连
custom_proxy_group=🍎 苹果服务`select`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🧩 专用线路`[]🌀 手动切换`[]🎯 全球直连
custom_proxy_group=🎮 国际游戏`select`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🧩 专用线路`[]🌀 手动切换`[]🎯 全球直连
custom_proxy_group=🎶 网易音乐`select`[]🎯 全球直连`[]🚀 节点选择`(网易|音乐|解锁|Music|NetEase)
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🎯 全球直连`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🌀 手动切换
custom_proxy_group=🎥 奈飞节点`select`(NF|奈飞|解锁|Netflix|NETFLIX|Media|原生)
custom_proxy_group=🧩 专用线路`select`(IPLC|IEPL|iplc|iepl|专线)
custom_proxy_group=🇭🇰 香港节点`select`(港|HK|England|Britain)
custom_proxy_group=🇨🇳 台湾节点`select`(台|新北|彰化|TW|Taiwan)
custom_proxy_group=🇺🇲 美国节点`select`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)
custom_proxy_group=🇯🇵 日本节点`select`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)
custom_proxy_group=🇸🇬 新加坡节点`select`(新加坡|坡|狮城|SG|Singapore)
custom_proxy_group=🇰🇷 韩国节点`select`(KR|Korea|KOR|首尔|韩|韓)
custom_proxy_group=🎯 全球直连`select`[]DIRECT
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT

enable_rule_generator=true
overwrite_original_rules=true

exclude_remarks=(剩余流量|到期时间|过期时间|官网地址|产品名称|先购买套餐|流量消耗|唯一官网|更新订阅)
exclude_remarks=(流量|本站|官网|过期|群|IPV6|永久)
exclude_remarks=(.*流量.*剩.*天)
exclude_remarks=(■等级警报■)
exclude_remarks=(\(限速\))
exclude_remarks=(\[限速\])
exclude_remarks=(\[游戏\])
exclude_remarks=(\[游戏专用\])
exclude_remarks=(\[将下线\])
exclude_remarks=(.*耗尽.*)
exclude_remarks=(近期下线)
exclude_remarks=(游戏专线)
exclude_remarks=(维护)
exclude_remarks=(测试节点)

udp_flag=true

rename=ぜんにっぽんくうゆ\s-\s@
rename=云\s-\s@
rename=(解锁|)(\|)(x.*)(\|V2ray)@$[$3]
rename=(..|...)([0-9][0-9][0-9][0-9]|[0-9][0-9][0-9])(\|)(Azure|HKT|CN2GIA)@$1$4$2
rename=^CordCloud - @
rename=(.*) (x.*[0-9]) (.*) (中转|直连|80端口)@$1 $3[$2]
rename=(.*) (x.*[0-9]) (..)(中转|直连|80端口)@$1 $3[$2]
rename=(V[0-9]-)(IEPL专线 |)(.*)( | \| )([0-9].*)(x$)@$3[x$5]
rename=(V[0-9]-)(IEPL专线 |)(.*)( )([0-9].*)(x) (原生IP)@$3[M][x$5]
rename=(.*)([0-9].*[0-9])(静态解锁|原生解锁|解锁|动态原生|原生|(原生\|IPV6解锁))(\|[\w].*[0-9])@$1$2[M]
rename=(.*)(\b[0-9][0-9]\b)(静态解锁|原生解锁|解锁|动态原生|原生|(原生\|IPV6解锁))@$1$2[M]
rename=(.*)([0-9].*[0-9])(标准|)(\|[\w].*[0-9])@$1$2
rename=(.*)(\[)(倍率:)(.*[0-9])(\])@$1[x$4]
rename=(\[x.*[0-9]\])(.*)@$2$1
rename=(.*)( )(.*[0-9])(倍率)@$1[x$3]
rename=((❖CN[0-9]❖)|^)(⓪|❶|❷|❸|❻)(TJ\.|gR\.|V2\.|H2\.|SS\.)@
;rename=^(.*)(HK(?!(B|T|G)))([\u4e00-\u9fa5])@香港 $3
rename=^(.*)(HK(?!B|G|T))([\u4e00-\u9fa5].*)@香港 $3
rename=^(HKBN)(.*)@香港HKBN $2
rename=^(HKG)(.*)@香港HKG $2
rename=^(HKT)(.*)@香港HKT $2
rename=^(HGC)(.*)@香港HGC $2
rename=^(WTT)(.*)@香港WTT $2
rename=^(US)(.*)@美国 $2
rename=^(JP)(.*)@日本 $2
rename=^(TW)(.*)@台湾 $2
rename=^(SG)(.*)@新加坡 $2
rename=^(RU)(.*)@俄罗斯 $2
rename=^(TR)(.*)@土耳其 $2
rename=^(UK)(.*)@英国 $2
rename=^(KR)(.*)@韩国 $2
rename=^(FR)(.*)@法国 $2
rename=^(CA)(.*)@加拿大 $2
rename=^(CN)(.*)@中国 $2
rename=^(RO)(.*)@罗马尼亚 $2
rename=^(BR)(.*)@巴西 $2
rename=商宽@
rename=移动@CM
rename=电信@CT
rename=联通@CU
rename=深港专线@深港
rename=(转)@▷
rename=[0-9]组@
rename=(--)@
rename=(◆)@
rename=(\[?\[NF\]|\[NF\*\]|\[BBC\]|\[abema\]|\[动画疯\]|Netflix|動畫瘋|\[Hulu\]|\[注册Netflix\]|\[HBO\]|\[TVB\]|\[D\+\]|\[Yp\]|Y2B P\]|解锁流媒体|原生IP)@[M]
rename=\[M\].*\[M\]@[M]
rename=\[CM\]|\[CU\]|\[BT\/PT专用\]|\[荐\]|\[Beta\]|\[移动\]|\[联通\]|\[综合\]|\[备用\]|\[阿里云\]|\[测试\]|\[v6\]|高速|100m限速|CDN加速|Game|PPCW|Sakura@
rename=\[0\.2\]@[x0.2]
rename=\[0\.5\]@[x0.5]
rename=\[0\.7\]@[x0.7]
rename=\[0\.8\]@[x0.8]
rename=\[0\.9\]@[x0.9]
rename=\[1\]@[x1]
rename=\[1\.2\]@[x1.2]
rename=\[1\.5\]@[x1.5]
rename=\[2\]@[x2]
rename=\[5\]@[x5]
rename=\[8\]@[x8]
rename=\[10\]@[x10]
;rename=(?!<=[\]|\)])$@[x1]
rename=\[\]@
